[package]
name = "vfw_primitives"
version = "0.1.0"
edition = "2021"
links = "vfw_primitives"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
vfw_build_utils.workspace = true

[features]
full_panic = []