[workspace]
members = [
    "vfw_hal",
    "vfw_core",
    "vfw_mailbox",
    "vfw_primitives",
    "vfw_utils",
]
resolver = "2"

[workspace.dependencies]
riscv = { version = "0.11" }
vfw_build_utils = {git = "https://github.com/shady831213/vfw_build_utils"}