[package]
name = "terminus_cosim_tests"
version = "0.1.0"
authors = ["shady831213 <shady831213@126.com>"]
edition = "2021"

[dependencies]
platform = { path = "..", package = "terminus_cosim"}

[build-dependencies]
build_tools = {path = "../../../build_tools"}